In [3]:
!pip3 install -U finance-datareader

Collecting finance-datareader
  Using cached finance_datareader-0.9.50-py3-none-any.whl (19 kB)
Collecting requests-file
  Using cached requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting lxml
  Using cached lxml-4.9.2-cp310-cp310-macosx_11_0_arm64.whl
Collecting pandas>=0.19.2
  Downloading pandas-1.5.3-cp310-cp310-macosx_11_0_arm64.whl (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 813.1 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting requests>=2.3.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 782.2 kB/s eta 0:00:00m eta 0:00:010:01:02
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/homebrew/lib/python3.10/site-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Collecting pytz>=2020.1
  Using cached pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.10/site-packages (from requests>=2.3.0->finance-datareader) (3.4)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.0.1-cp310-cp310-macosx_11_0_arm64.whl (122 kB)
Requirement already satisfied: six in /opt/homebrew/lib/python3.10/site-packages (from requests-file->finance-datareader) (1.16.0)
Installing collected packages: pytz, charset-normalizer, urllib3, tqdm, numpy, lxml, certifi, requests, pandas, requests-file, finance-datareader
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 finance-datareader-0.9.50 lxml-4.9.2 numpy-1.24.2 pandas-1.5.3 pytz-2022.7.1 requests-2.28.2 requests-file-1.5.1 tqdm-4.64.1 urllib3-1.26.14

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python3.10 -m pip install --upgrade pip

In [5]:
import FinanceDataReader as fdr

fdr.__version__

'0.9.50'

In [6]:
 fdr.__version__

'0.9.50'

In [10]:
df_krx = fdr.StockListing('KRX')

In [11]:
df_krx.shape

(2700, 17)

In [12]:
df_krx

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,61300,2,-700,-1.13,62300,62600,61300,10308143,638634052687,365947670315000,5969782550,STK
1,373220,KR7373220003,LG에너지솔루션,KOSPI,,511000,1,4000,0.79,508000,522000,507000,239646,123155230000,119574000000000,234000000,STK
2,000660,KR7000660001,SK하이닉스,KOSPI,,91000,2,-1700,-1.83,93500,94000,91000,2496352,230723303704,66248215215000,728002365,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,783000,2,-6000,-0.76,789000,790000,781000,39167,30725679000,55729242000000,71174000,STK
4,051910,KR7051910008,LG화학,KOSPI,,669000,1,1000,0.15,668000,686000,666000,145162,97814598000,47226277467000,70592343,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2695,267810,KR7267810000,앙츠,KONEX,일반기업부,1093,0,0,0.00,0,0,0,0,0,1953191000,1787000,KNX
2696,215050,KR7215050006,비엔디생활건강,KONEX,일반기업부,912,0,0,0.00,0,0,0,0,0,1934959392,2121666,KNX
2697,267060,KR7267060002,명진홀딩스,KONEX,일반기업부,181,0,0,0.00,0,0,0,0,0,1654666524,9141804,KNX
2698,308700,KR7308700004,테크엔,KONEX,일반기업부,410,1,52,14.53,370,411,370,367,150028,1640000000,4000000,KNX
2699,322190,KR7322190000,베른,KONEX,일반기업부,104,2,-1,-0.95,120,120,104,145,15689,928220488,8925197,KNX

In [13]:
import datetime

# 시작일자와 종료일자 설정
end_date = datetime.datetime.now()
start_date = end_date - datetime.timedelta(days=365)

# 삼성전자의 주가 데이터 가져오기
samsung = fdr.DataReader('005930', start_date, end_date)

# 결과 출력
print(samsung)

             Open   High    Low  Close    Volume    Change
Date
2022-02-28  71100  72100  71000  72100  17781783  0.002782
2022-03-02  72300  72400  71500  71700  12481430 -0.005548
2022-03-03  72300  73100  72200  72900  13232638  0.016736
2022-03-04  72700  72700  71200  71500  13409634 -0.019204
2022-03-07  70000  70600  69900  70100  18617138 -0.019580
...           ...    ...    ...    ...       ...       ...
2023-02-20  62900  63000  61800  62700  12908073  0.001597
2023-02-21  62700  62800  62000  62100   7665046 -0.009569
2023-02-22  61500  61800  61000  61100  11959088 -0.016103
2023-02-23  61700  62500  61500  62000  13047099  0.014730
2023-02-24  62300  62600  61300  61300  10134614 -0.011290

[247 rows x 6 columns]

In [15]:
import pandas as pd

# 삼성전자 종목코드: 005930
df = fdr.DataReader('005930', '2022-02-26', '2021-02-27', 'minute1')

# 인덱스를 datetime 형태로 변경
df.index = pd.to_datetime(df.index)

print(df)

HTTP Error 400: Bad Request  - symbol "005930"not found or invalid periods
Empty DataFrame
Columns: []
Index: []

In [18]:
import matplotlib.pyplot as plt


# 삼성전자 종목코드: 005930
df = fdr.DataReader('005930', '2022-02-26', '2021-02-27')

# 데이터 시각화
plt.plot(df.index, df['Close'])
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Samsung Electronics Stock Price')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'